# Generated by Django 4.1.3 on 2023-06-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mgame", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="room_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="user1ingame",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="user2ingame",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
